-keep class com.lethao.kidcare.MainActivity { *; }
-keep class com.lethao.kidcare.KidPermissionsPlugin { *; }
-keep class com.getcapacitor.BridgeActivity { *; }
-keep class com.getcapacitor.Bridge { *; }
